language: elixir
elixir:
- 1.6.4
otp_release:
- 20.0.5
before_install:
- openssl aes-256-cbc -K $encrypted_2925220642eb_key -iv $encrypted_2925220642eb_iv
  -in .travis/travis_dokku.enc -out .travis/travis_dokku -d
deploy:
  provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
